/* File: fort_scmodule.c
 * This file is auto-generated with f2py (version:1.26.4).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Sun Mar  8 21:25:39 2026
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

#ifndef PY_SSIZE_T_CLEAN
#define PY_SSIZE_T_CLEAN
#endif /* PY_SSIZE_T_CLEAN */

/* Unconditionally included */
#include <Python.h>
#include <numpy/npy_os.h>

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "fortranobject.h"
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *fort_sc_error;
static PyObject *fort_sc_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
typedef struct {double r,i;} complex_double;

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/

/* See fortranobject.h for definitions. The macros here are provided for BC. */
#define rank f2py_rank
#define shape f2py_shape
#define fshape f2py_shape
#define len f2py_len
#define flen f2py_flen
#define slen f2py_slen
#define size f2py_size


#define CHECKSCALAR(check,tcheck,name,show,var)\
    if (!(check)) {\
        char errstring[256];\
        sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
        PyErr_SetString(fort_sc_error,errstring);\
        /*goto capi_fail;*/\
    } else 

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif


#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/

static int
int_from_pyobj(int* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;

    if (PyLong_Check(obj)) {
        *v = Npy__PyLong_AsInt(obj);
        return !(*v == -1 && PyErr_Occurred());
    }

    tmp = PyNumber_Long(obj);
    if (tmp) {
        *v = Npy__PyLong_AsInt(tmp);
        Py_DECREF(tmp);
        return !(*v == -1 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj)) {
        PyErr_Clear();
        tmp = PyObject_GetAttrString(obj,"real");
    }
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj)) {
        /*pass*/;
    }
    else if (PySequence_Check(obj)) {
        PyErr_Clear();
        tmp = PySequence_GetItem(obj, 0);
    }

    if (tmp) {
        if (int_from_pyobj(v, tmp, errmess)) {
            Py_DECREF(tmp);
            return 1;
        }
        Py_DECREF(tmp);
    }

    {
        PyObject* err = PyErr_Occurred();
        if (err == NULL) {
            err = fort_sc_error;
        }
        PyErr_SetString(err, errmess);
    }
    return 0;
}


static int
double_from_pyobj(double* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;
    if (PyFloat_Check(obj)) {
        *v = PyFloat_AsDouble(obj);
        return !(*v == -1.0 && PyErr_Occurred());
    }

    tmp = PyNumber_Float(obj);
    if (tmp) {
        *v = PyFloat_AsDouble(tmp);
        Py_DECREF(tmp);
        return !(*v == -1.0 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj)) {
        PyErr_Clear();
        tmp = PyObject_GetAttrString(obj,"real");
    }
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj)) {
        /*pass*/;
    }
    else if (PySequence_Check(obj)) {
        PyErr_Clear();
        tmp = PySequence_GetItem(obj, 0);
    }

    if (tmp) {
        if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = fort_sc_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/******************************** compute_dos ********************************/
static char doc_f2py_rout_fort_sc_hamiltonians_sympy_compute_dos[] = "\
dos = compute_dos(n_k_points,n_k_points_refined,t_sigma,t_pi,lambda_soc,t_rashba,delta_tri,mu,g,mu_b,b,theta_b,phi_b,zeta,ir_number,xi,dos_energies,[n_xi,n_energy_points_dos])\n\nWrapper for ``compute_dos``.\
\n\nParameters\n----------\n"
"n_k_points : input int\n"
"n_k_points_refined : input int\n"
"t_sigma : input float\n"
"t_pi : input float\n"
"lambda_soc : input float\n"
"t_rashba : input float\n"
"delta_tri : input float\n"
"mu : input float\n"
"g : input float\n"
"mu_b : input float\n"
"b : input float\n"
"theta_b : input float\n"
"phi_b : input float\n"
"zeta : input float\n"
"ir_number : input int\n"
"xi : input rank-1 array('D') with bounds (n_xi)\n"
"dos_energies : input rank-1 array('d') with bounds (n_energy_points_dos)\n"
"\nOther Parameters\n----------------\n"
"n_xi : input int, optional\n    Default: shape(xi, 0)\n"
"n_energy_points_dos : input int, optional\n    Default: shape(dos_energies, 0)\n"
"\nReturns\n-------\n"
"dos : rank-2 array('d') with bounds (n_energy_points_dos,24)";
/*  */
static PyObject *f2py_rout_fort_sc_hamiltonians_sympy_compute_dos(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,int*,complex_double*,double*,double*,int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int n_k_points = 0;
    PyObject *n_k_points_capi = Py_None;
    int n_k_points_refined = 0;
    PyObject *n_k_points_refined_capi = Py_None;
    double t_sigma = 0;
    PyObject *t_sigma_capi = Py_None;
    double t_pi = 0;
    PyObject *t_pi_capi = Py_None;
    double lambda_soc = 0;
    PyObject *lambda_soc_capi = Py_None;
    double t_rashba = 0;
    PyObject *t_rashba_capi = Py_None;
    double delta_tri = 0;
    PyObject *delta_tri_capi = Py_None;
    double mu = 0;
    PyObject *mu_capi = Py_None;
    double g = 0;
    PyObject *g_capi = Py_None;
    double mu_b = 0;
    PyObject *mu_b_capi = Py_None;
    double b = 0;
    PyObject *b_capi = Py_None;
    double theta_b = 0;
    PyObject *theta_b_capi = Py_None;
    double phi_b = 0;
    PyObject *phi_b_capi = Py_None;
    double zeta = 0;
    PyObject *zeta_capi = Py_None;
    int ir_number = 0;
    PyObject *ir_number_capi = Py_None;
    complex_double *xi = NULL;
    npy_intp xi_Dims[1] = {-1};
    const int xi_Rank = 1;
    PyArrayObject *capi_xi_as_array = NULL;
    int capi_xi_intent = 0;
    PyObject *xi_capi = Py_None;
    double *dos_energies = NULL;
    npy_intp dos_energies_Dims[1] = {-1};
    const int dos_energies_Rank = 1;
    PyArrayObject *capi_dos_energies_as_array = NULL;
    int capi_dos_energies_intent = 0;
    PyObject *dos_energies_capi = Py_None;
    double *dos = NULL;
    npy_intp dos_Dims[2] = {-1, -1};
    const int dos_Rank = 2;
    PyArrayObject *capi_dos_as_array = NULL;
    int capi_dos_intent = 0;
    int n_xi = 0;
    PyObject *n_xi_capi = Py_None;
    int n_energy_points_dos = 0;
    PyObject *n_energy_points_dos_capi = Py_None;
    static char *capi_kwlist[] = {"n_k_points","n_k_points_refined","t_sigma","t_pi","lambda_soc","t_rashba","delta_tri","mu","g","mu_b","b","theta_b","phi_b","zeta","ir_number","xi","dos_energies","n_xi","n_energy_points_dos",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOOOOOOOOOOOOOOO|OO:fort_sc.hamiltonians_sympy.compute_dos",\
        capi_kwlist,&n_k_points_capi,&n_k_points_refined_capi,&t_sigma_capi,&t_pi_capi,&lambda_soc_capi,&t_rashba_capi,&delta_tri_capi,&mu_capi,&g_capi,&mu_b_capi,&b_capi,&theta_b_capi,&phi_b_capi,&zeta_capi,&ir_number_capi,&xi_capi,&dos_energies_capi,&n_xi_capi,&n_energy_points_dos_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable n_k_points */
        f2py_success = int_from_pyobj(&n_k_points,n_k_points_capi,"fort_sc.hamiltonians_sympy.compute_dos() 1st argument (n_k_points) can't be converted to int");
    if (f2py_success) {
    /* Processing variable n_k_points_refined */
        f2py_success = int_from_pyobj(&n_k_points_refined,n_k_points_refined_capi,"fort_sc.hamiltonians_sympy.compute_dos() 2nd argument (n_k_points_refined) can't be converted to int");
    if (f2py_success) {
    /* Processing variable t_sigma */
        f2py_success = double_from_pyobj(&t_sigma,t_sigma_capi,"fort_sc.hamiltonians_sympy.compute_dos() 3rd argument (t_sigma) can't be converted to double");
    if (f2py_success) {
    /* Processing variable t_pi */
        f2py_success = double_from_pyobj(&t_pi,t_pi_capi,"fort_sc.hamiltonians_sympy.compute_dos() 4th argument (t_pi) can't be converted to double");
    if (f2py_success) {
    /* Processing variable lambda_soc */
        f2py_success = double_from_pyobj(&lambda_soc,lambda_soc_capi,"fort_sc.hamiltonians_sympy.compute_dos() 5th argument (lambda_soc) can't be converted to double");
    if (f2py_success) {
    /* Processing variable t_rashba */
        f2py_success = double_from_pyobj(&t_rashba,t_rashba_capi,"fort_sc.hamiltonians_sympy.compute_dos() 6th argument (t_rashba) can't be converted to double");
    if (f2py_success) {
    /* Processing variable delta_tri */
        f2py_success = double_from_pyobj(&delta_tri,delta_tri_capi,"fort_sc.hamiltonians_sympy.compute_dos() 7th argument (delta_tri) can't be converted to double");
    if (f2py_success) {
    /* Processing variable mu */
        f2py_success = double_from_pyobj(&mu,mu_capi,"fort_sc.hamiltonians_sympy.compute_dos() 8th argument (mu) can't be converted to double");
    if (f2py_success) {
    /* Processing variable g */
        f2py_success = double_from_pyobj(&g,g_capi,"fort_sc.hamiltonians_sympy.compute_dos() 9th argument (g) can't be converted to double");
    if (f2py_success) {
    /* Processing variable mu_b */
        f2py_success = double_from_pyobj(&mu_b,mu_b_capi,"fort_sc.hamiltonians_sympy.compute_dos() 10th argument (mu_b) can't be converted to double");
    if (f2py_success) {
    /* Processing variable b */
        f2py_success = double_from_pyobj(&b,b_capi,"fort_sc.hamiltonians_sympy.compute_dos() 11st argument (b) can't be converted to double");
    if (f2py_success) {
    /* Processing variable theta_b */
        f2py_success = double_from_pyobj(&theta_b,theta_b_capi,"fort_sc.hamiltonians_sympy.compute_dos() 12nd argument (theta_b) can't be converted to double");
    if (f2py_success) {
    /* Processing variable phi_b */
        f2py_success = double_from_pyobj(&phi_b,phi_b_capi,"fort_sc.hamiltonians_sympy.compute_dos() 13rd argument (phi_b) can't be converted to double");
    if (f2py_success) {
    /* Processing variable zeta */
        f2py_success = double_from_pyobj(&zeta,zeta_capi,"fort_sc.hamiltonians_sympy.compute_dos() 14th argument (zeta) can't be converted to double");
    if (f2py_success) {
    /* Processing variable ir_number */
        f2py_success = int_from_pyobj(&ir_number,ir_number_capi,"fort_sc.hamiltonians_sympy.compute_dos() 15th argument (ir_number) can't be converted to int");
    if (f2py_success) {
    /* Processing variable xi */
    ;
    capi_xi_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "fort_sc.fort_sc.hamiltonians_sympy.compute_dos: failed to create array from the 16th argument `xi`";
    capi_xi_as_array = ndarray_from_pyobj(  NPY_CDOUBLE,1,xi_Dims,xi_Rank,  capi_xi_intent,xi_capi,capi_errmess);
    if (capi_xi_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = fort_sc_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        xi = (complex_double *)(PyArray_DATA(capi_xi_as_array));

    /* Processing variable dos_energies */
    ;
    capi_dos_energies_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "fort_sc.fort_sc.hamiltonians_sympy.compute_dos: failed to create array from the 17th argument `dos_energies`";
    capi_dos_energies_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,dos_energies_Dims,dos_energies_Rank,  capi_dos_energies_intent,dos_energies_capi,capi_errmess);
    if (capi_dos_energies_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = fort_sc_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        dos_energies = (double *)(PyArray_DATA(capi_dos_energies_as_array));

    /* Processing variable n_xi */
    if (n_xi_capi == Py_None) n_xi = shape(xi, 0); else
        f2py_success = int_from_pyobj(&n_xi,n_xi_capi,"fort_sc.hamiltonians_sympy.compute_dos() 1st keyword (n_xi) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(xi, 0) == n_xi,"shape(xi, 0) == n_xi","1st keyword n_xi","compute_dos:n_xi=%d",n_xi) {
    /* Processing variable n_energy_points_dos */
    if (n_energy_points_dos_capi == Py_None) n_energy_points_dos = shape(dos_energies, 0); else
        f2py_success = int_from_pyobj(&n_energy_points_dos,n_energy_points_dos_capi,"fort_sc.hamiltonians_sympy.compute_dos() 2nd keyword (n_energy_points_dos) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(dos_energies, 0) == n_energy_points_dos,"shape(dos_energies, 0) == n_energy_points_dos","2nd keyword n_energy_points_dos","compute_dos:n_energy_points_dos=%d",n_energy_points_dos) {
    /* Processing variable dos */
    dos_Dims[0]=n_energy_points_dos,dos_Dims[1]=24;
    capi_dos_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char * capi_errmess = "fort_sc.fort_sc.hamiltonians_sympy.compute_dos: failed to create array from the hidden `dos`";
    capi_dos_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,dos_Dims,dos_Rank,  capi_dos_intent,Py_None,capi_errmess);
    if (capi_dos_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = fort_sc_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        dos = (double *)(PyArray_DATA(capi_dos_as_array));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(&n_k_points,&n_k_points_refined,&t_sigma,&t_pi,&lambda_soc,&t_rashba,&delta_tri,&mu,&g,&mu_b,&b,&theta_b,&phi_b,&zeta,&ir_number,xi,dos_energies,dos,&n_xi,&n_energy_points_dos);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("N",capi_dos_as_array);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    }  /* if (capi_dos_as_array == NULL) ... else of dos */
    /* End of cleaning variable dos */
    } /*CHECKSCALAR(shape(dos_energies, 0) == n_energy_points_dos)*/
    } /*if (f2py_success) of n_energy_points_dos*/
    /* End of cleaning variable n_energy_points_dos */
    } /*CHECKSCALAR(shape(xi, 0) == n_xi)*/
    } /*if (f2py_success) of n_xi*/
    /* End of cleaning variable n_xi */
    if((PyObject *)capi_dos_energies_as_array!=dos_energies_capi) {
        Py_XDECREF(capi_dos_energies_as_array); }
    }  /* if (capi_dos_energies_as_array == NULL) ... else of dos_energies */
    /* End of cleaning variable dos_energies */
    if((PyObject *)capi_xi_as_array!=xi_capi) {
        Py_XDECREF(capi_xi_as_array); }
    }  /* if (capi_xi_as_array == NULL) ... else of xi */
    /* End of cleaning variable xi */
    } /*if (f2py_success) of ir_number*/
    /* End of cleaning variable ir_number */
    } /*if (f2py_success) of zeta*/
    /* End of cleaning variable zeta */
    } /*if (f2py_success) of phi_b*/
    /* End of cleaning variable phi_b */
    } /*if (f2py_success) of theta_b*/
    /* End of cleaning variable theta_b */
    } /*if (f2py_success) of b*/
    /* End of cleaning variable b */
    } /*if (f2py_success) of mu_b*/
    /* End of cleaning variable mu_b */
    } /*if (f2py_success) of g*/
    /* End of cleaning variable g */
    } /*if (f2py_success) of mu*/
    /* End of cleaning variable mu */
    } /*if (f2py_success) of delta_tri*/
    /* End of cleaning variable delta_tri */
    } /*if (f2py_success) of t_rashba*/
    /* End of cleaning variable t_rashba */
    } /*if (f2py_success) of lambda_soc*/
    /* End of cleaning variable lambda_soc */
    } /*if (f2py_success) of t_pi*/
    /* End of cleaning variable t_pi */
    } /*if (f2py_success) of t_sigma*/
    /* End of cleaning variable t_sigma */
    } /*if (f2py_success) of n_k_points_refined*/
    /* End of cleaning variable n_k_points_refined */
    } /*if (f2py_success) of n_k_points*/
    /* End of cleaning variable n_k_points */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/***************************** end of compute_dos *****************************/

/**************************** compute_free_energy ****************************/
static char doc_f2py_rout_fort_sc_hamiltonians_sympy_compute_free_energy[] = "\
free_energy = compute_free_energy(n_k_points,t_sigma,t_pi,lambda_soc,t_rashba,delta_tri,mu,g,mu_b,b,theta_b,phi_b,t,ir_number,xi,[n_xi])\n\nWrapper for ``compute_free_energy``.\
\n\nParameters\n----------\n"
"n_k_points : input int\n"
"t_sigma : input float\n"
"t_pi : input float\n"
"lambda_soc : input float\n"
"t_rashba : input float\n"
"delta_tri : input float\n"
"mu : input float\n"
"g : input float\n"
"mu_b : input float\n"
"b : input float\n"
"theta_b : input float\n"
"phi_b : input float\n"
"t : input float\n"
"ir_number : input int\n"
"xi : input rank-1 array('D') with bounds (n_xi)\n"
"\nOther Parameters\n----------------\n"
"n_xi : input int, optional\n    Default: shape(xi, 0)\n"
"\nReturns\n-------\n"
"free_energy : float";
/*  */
static PyObject *f2py_rout_fort_sc_hamiltonians_sympy_compute_free_energy(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,int*,complex_double*,int*,double*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int n_k_points = 0;
    PyObject *n_k_points_capi = Py_None;
    double t_sigma = 0;
    PyObject *t_sigma_capi = Py_None;
    double t_pi = 0;
    PyObject *t_pi_capi = Py_None;
    double lambda_soc = 0;
    PyObject *lambda_soc_capi = Py_None;
    double t_rashba = 0;
    PyObject *t_rashba_capi = Py_None;
    double delta_tri = 0;
    PyObject *delta_tri_capi = Py_None;
    double mu = 0;
    PyObject *mu_capi = Py_None;
    double g = 0;
    PyObject *g_capi = Py_None;
    double mu_b = 0;
    PyObject *mu_b_capi = Py_None;
    double b = 0;
    PyObject *b_capi = Py_None;
    double theta_b = 0;
    PyObject *theta_b_capi = Py_None;
    double phi_b = 0;
    PyObject *phi_b_capi = Py_None;
    double t = 0;
    PyObject *t_capi = Py_None;
    int ir_number = 0;
    PyObject *ir_number_capi = Py_None;
    complex_double *xi = NULL;
    npy_intp xi_Dims[1] = {-1};
    const int xi_Rank = 1;
    PyArrayObject *capi_xi_as_array = NULL;
    int capi_xi_intent = 0;
    PyObject *xi_capi = Py_None;
    int n_xi = 0;
    PyObject *n_xi_capi = Py_None;
    double free_energy = 0;
    static char *capi_kwlist[] = {"n_k_points","t_sigma","t_pi","lambda_soc","t_rashba","delta_tri","mu","g","mu_b","b","theta_b","phi_b","t","ir_number","xi","n_xi",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOOOOOOOOOOOOO|O:fort_sc.hamiltonians_sympy.compute_free_energy",\
        capi_kwlist,&n_k_points_capi,&t_sigma_capi,&t_pi_capi,&lambda_soc_capi,&t_rashba_capi,&delta_tri_capi,&mu_capi,&g_capi,&mu_b_capi,&b_capi,&theta_b_capi,&phi_b_capi,&t_capi,&ir_number_capi,&xi_capi,&n_xi_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable n_k_points */
        f2py_success = int_from_pyobj(&n_k_points,n_k_points_capi,"fort_sc.hamiltonians_sympy.compute_free_energy() 1st argument (n_k_points) can't be converted to int");
    if (f2py_success) {
    /* Processing variable t_sigma */
        f2py_success = double_from_pyobj(&t_sigma,t_sigma_capi,"fort_sc.hamiltonians_sympy.compute_free_energy() 2nd argument (t_sigma) can't be converted to double");
    if (f2py_success) {
    /* Processing variable t_pi */
        f2py_success = double_from_pyobj(&t_pi,t_pi_capi,"fort_sc.hamiltonians_sympy.compute_free_energy() 3rd argument (t_pi) can't be converted to double");
    if (f2py_success) {
    /* Processing variable lambda_soc */
        f2py_success = double_from_pyobj(&lambda_soc,lambda_soc_capi,"fort_sc.hamiltonians_sympy.compute_free_energy() 4th argument (lambda_soc) can't be converted to double");
    if (f2py_success) {
    /* Processing variable t_rashba */
        f2py_success = double_from_pyobj(&t_rashba,t_rashba_capi,"fort_sc.hamiltonians_sympy.compute_free_energy() 5th argument (t_rashba) can't be converted to double");
    if (f2py_success) {
    /* Processing variable delta_tri */
        f2py_success = double_from_pyobj(&delta_tri,delta_tri_capi,"fort_sc.hamiltonians_sympy.compute_free_energy() 6th argument (delta_tri) can't be converted to double");
    if (f2py_success) {
    /* Processing variable mu */
        f2py_success = double_from_pyobj(&mu,mu_capi,"fort_sc.hamiltonians_sympy.compute_free_energy() 7th argument (mu) can't be converted to double");
    if (f2py_success) {
    /* Processing variable g */
        f2py_success = double_from_pyobj(&g,g_capi,"fort_sc.hamiltonians_sympy.compute_free_energy() 8th argument (g) can't be converted to double");
    if (f2py_success) {
    /* Processing variable mu_b */
        f2py_success = double_from_pyobj(&mu_b,mu_b_capi,"fort_sc.hamiltonians_sympy.compute_free_energy() 9th argument (mu_b) can't be converted to double");
    if (f2py_success) {
    /* Processing variable b */
        f2py_success = double_from_pyobj(&b,b_capi,"fort_sc.hamiltonians_sympy.compute_free_energy() 10th argument (b) can't be converted to double");
    if (f2py_success) {
    /* Processing variable theta_b */
        f2py_success = double_from_pyobj(&theta_b,theta_b_capi,"fort_sc.hamiltonians_sympy.compute_free_energy() 11st argument (theta_b) can't be converted to double");
    if (f2py_success) {
    /* Processing variable phi_b */
        f2py_success = double_from_pyobj(&phi_b,phi_b_capi,"fort_sc.hamiltonians_sympy.compute_free_energy() 12nd argument (phi_b) can't be converted to double");
    if (f2py_success) {
    /* Processing variable t */
        f2py_success = double_from_pyobj(&t,t_capi,"fort_sc.hamiltonians_sympy.compute_free_energy() 13rd argument (t) can't be converted to double");
    if (f2py_success) {
    /* Processing variable ir_number */
        f2py_success = int_from_pyobj(&ir_number,ir_number_capi,"fort_sc.hamiltonians_sympy.compute_free_energy() 14th argument (ir_number) can't be converted to int");
    if (f2py_success) {
    /* Processing variable xi */
    ;
    capi_xi_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "fort_sc.fort_sc.hamiltonians_sympy.compute_free_energy: failed to create array from the 15th argument `xi`";
    capi_xi_as_array = ndarray_from_pyobj(  NPY_CDOUBLE,1,xi_Dims,xi_Rank,  capi_xi_intent,xi_capi,capi_errmess);
    if (capi_xi_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = fort_sc_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        xi = (complex_double *)(PyArray_DATA(capi_xi_as_array));

    /* Processing variable free_energy */
    /* Processing variable n_xi */
    if (n_xi_capi == Py_None) n_xi = shape(xi, 0); else
        f2py_success = int_from_pyobj(&n_xi,n_xi_capi,"fort_sc.hamiltonians_sympy.compute_free_energy() 1st keyword (n_xi) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(xi, 0) == n_xi,"shape(xi, 0) == n_xi","1st keyword n_xi","compute_free_energy:n_xi=%d",n_xi) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(&n_k_points,&t_sigma,&t_pi,&lambda_soc,&t_rashba,&delta_tri,&mu,&g,&mu_b,&b,&theta_b,&phi_b,&t,&ir_number,xi,&n_xi,&free_energy);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("d",free_energy);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    } /*CHECKSCALAR(shape(xi, 0) == n_xi)*/
    } /*if (f2py_success) of n_xi*/
    /* End of cleaning variable n_xi */
    /* End of cleaning variable free_energy */
    if((PyObject *)capi_xi_as_array!=xi_capi) {
        Py_XDECREF(capi_xi_as_array); }
    }  /* if (capi_xi_as_array == NULL) ... else of xi */
    /* End of cleaning variable xi */
    } /*if (f2py_success) of ir_number*/
    /* End of cleaning variable ir_number */
    } /*if (f2py_success) of t*/
    /* End of cleaning variable t */
    } /*if (f2py_success) of phi_b*/
    /* End of cleaning variable phi_b */
    } /*if (f2py_success) of theta_b*/
    /* End of cleaning variable theta_b */
    } /*if (f2py_success) of b*/
    /* End of cleaning variable b */
    } /*if (f2py_success) of mu_b*/
    /* End of cleaning variable mu_b */
    } /*if (f2py_success) of g*/
    /* End of cleaning variable g */
    } /*if (f2py_success) of mu*/
    /* End of cleaning variable mu */
    } /*if (f2py_success) of delta_tri*/
    /* End of cleaning variable delta_tri */
    } /*if (f2py_success) of t_rashba*/
    /* End of cleaning variable t_rashba */
    } /*if (f2py_success) of lambda_soc*/
    /* End of cleaning variable lambda_soc */
    } /*if (f2py_success) of t_pi*/
    /* End of cleaning variable t_pi */
    } /*if (f2py_success) of t_sigma*/
    /* End of cleaning variable t_sigma */
    } /*if (f2py_success) of n_k_points*/
    /* End of cleaning variable n_k_points */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/************************* end of compute_free_energy *************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/

static FortranDataDef f2py_hamiltonians_sympy_def[] = {
  {"compute_dos",-1,{{-1}},0,0,NULL,(void *)f2py_rout_fort_sc_hamiltonians_sympy_compute_dos,doc_f2py_rout_fort_sc_hamiltonians_sympy_compute_dos},
  {"compute_free_energy",-1,{{-1}},0,0,NULL,(void *)f2py_rout_fort_sc_hamiltonians_sympy_compute_free_energy,doc_f2py_rout_fort_sc_hamiltonians_sympy_compute_free_energy},
  {NULL}
};

static void f2py_setup_hamiltonians_sympy(char *compute_dos,char *compute_free_energy) {
  int i_f2py=0;
  f2py_hamiltonians_sympy_def[i_f2py++].data = compute_dos;
  f2py_hamiltonians_sympy_def[i_f2py++].data = compute_free_energy;
}
extern void F_FUNC_US(f2pyinithamiltonians_sympy,F2PYINITHAMILTONIANS_SYMPY)(void (*)(char *,char *));
static void f2py_init_hamiltonians_sympy(void) {
  F_FUNC_US(f2pyinithamiltonians_sympy,F2PYINITHAMILTONIANS_SYMPY)(f2py_setup_hamiltonians_sympy);
}

/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {

/*eof routine_defs*/
    {NULL}
};

static PyMethodDef f2py_module_methods[] = {

    {NULL,NULL}
};

static struct PyModuleDef moduledef = {
    PyModuleDef_HEAD_INIT,
    "fort_sc",
    NULL,
    -1,
    f2py_module_methods,
    NULL,
    NULL,
    NULL,
    NULL
};

PyMODINIT_FUNC PyInit_fort_sc(void) {
    int i;
    PyObject *m,*d, *s, *tmp;
    m = fort_sc_module = PyModule_Create(&moduledef);
    Py_SET_TYPE(&PyFortran_Type, &PyType_Type);
    import_array();
    if (PyErr_Occurred())
        {PyErr_SetString(PyExc_ImportError, "can't initialize module fort_sc (failed to import numpy)"); return m;}
    d = PyModule_GetDict(m);
    s = PyUnicode_FromString("1.26.4");
    PyDict_SetItemString(d, "__version__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString(
        "This module 'fort_sc' is auto-generated with f2py (version:1.26.4).\nFunctions:\n"
"Fortran 90/95 modules:\n""  hamiltonians_sympy --- compute_dos(),compute_free_energy()"".");
    PyDict_SetItemString(d, "__doc__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString("1.26.4");
    PyDict_SetItemString(d, "__f2py_numpy_version__", s);
    Py_DECREF(s);
    fort_sc_error = PyErr_NewException ("fort_sc.error", NULL, NULL);
    /*
     * Store the error object inside the dict, so that it could get deallocated.
     * (in practice, this is a module, so it likely will not and cannot.)
     */
    PyDict_SetItemString(d, "_fort_sc_error", fort_sc_error);
    Py_DECREF(fort_sc_error);
    for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
        tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
        PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
        Py_DECREF(tmp);
    }


/*eof initf2pywraphooks*/
  PyDict_SetItemString(d, "hamiltonians_sympy", PyFortranObject_New(f2py_hamiltonians_sympy_def,f2py_init_hamiltonians_sympy));
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
    if (! PyErr_Occurred())
        on_exit(f2py_report_on_exit,(void*)"fort_sc");
#endif
    return m;
}
#ifdef __cplusplus
}
#endif
