!     -*- f90 -*-
!     This file is autogenerated with f2py (version:1.26.4)
!     It contains Fortran 90 wrappers to fortran functions.

      
      subroutine f2pyinithamiltonians_sympy(f2pysetupfunc)
      use hamiltonians_sympy, only : compute_dos
      use hamiltonians_sympy, only : compute_free_energy
      external f2pysetupfunc
      call f2pysetupfunc(compute_dos,compute_free_energy)
      end subroutine f2pyinithamiltonians_sympy


